title: "Kestrun documentation"
description: "The official kestrun documentation"
theme: just-the-docs

plugins:
  - jekyll-default-layout
  - jekyll-seo-tag
  
url: https://kestrun.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


 
 
logo: "docs//kestrel_logo_transparent.png"
color_scheme: light
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation settings
nav_sort: case_insensitive
nav_external_links:
  - title: Kestrun on GitHub
    url: https://github.com/kestrun/kestrun
    hide_icon: false
 

# Footer settings
footer_content: "Copyright &copy; 2025 Kestrun. Distributed by an <a href=\"https://github.com/kestrun/kestrun/blob/master/LICENSE.txt\">MIT license.</a>"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
 

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
heading_anchors: true
 

# Google Analytics Tracking (optional)
# ga_tracking: G-XXXXXXXXXX
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/false)

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false